# ERTA ALE

# ----> erta ale (after 20170101 and before 20170401)
# python Sentinel_download.py --lat 13.60 --lon 40.66 -d 20170101 -f 20170401 -a apihub_seb.txt -s S1*SLC -n  
# python Sentinel_download.py --lat 13.60 --lon 40.66 -d 20170101 -f 20170401 -a apihub_seb.txt -s S1*SLC__1SSV -w /home/khola/DATA/data_satellite/ERTAALE/new


# === search query options (scihub)
optn_search:
  filename: S1*IW_SLC* #SLC__1SSV*
  #filename: S2A_MSI*
  #ingestiondate: "[2017-01-25T00:00:00.000Z TO 2017-02-15T00:00:00.000Z]"

  #platformname: Sentinel-2
  #productType: SLC
  #polarisationmode: VV
  #sensoroperationalmode: IW
  footprint: [13.60, 40.66]
  #ingestiondate: "[2017-01-01T00:00:00.000Z TO 2017-04-01T00:00:00.000Z]"

  maxrecords: 50
  orderby: ingestiondate desc



# === download options
optn_download:
  product_node: quicklook             # S1 options: quicklook, fullproduct
  download_dir: /home/sebastien/DATA/data_satellite/ertaale_cron/