# ETNA

# Download all prodcuts available
# Usage:
#   import fetchme
#   obj = fetchme.Scihub()
#   obj.scihub_search(configfile='./conf/_config_etna_archive.yml')

# === search query options (scihub)
optn_search:
  #filename: S1*IW_SLC__1SSV*
  filename: S1*IW_SLC*
  #platformname: Sentinel-1
  #productType: SLC
  #polarisationmode: VV
  #sensoroperationalmode: IW
  footprint: [37.73, 15.00]
  ingestiondate: "[2017-01-01T00:00:00.000Z TO NOW]"
  #ingestiondate: "[2016-12-01T00:00:00.000Z TO NOW]"
  maxrecords: 100
  orderby: ingestiondate desc



# === download options
# optn_download:
#   download_pnode: fullproduct             # S1 options: quicklook, fullproduct
#   download_dir: /home/sebastien/DATA/data_satellite/etna/